### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by ZHOU-ZHOU-YI** [JCruan519/EGE-UNet#5]
98%|█████████▊| 45/46 [00:37<00:00,  1.21it/s]tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0')
100%|██████████| 46/46 [00:38<00:00,  1.20it/s]
tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0')
Traceback (most recent call last):
  File "P:\CJJ\EGE-UNet-main\train.py", line 169, in <module>
    main(config)
  File "P:\CJJ\EGE-UNet-main\train.py", line 154, in main
    loss = test_one_epoch(
  File "P:\CJJ\EGE-UNet-main\engine.py", line 147, in test_one_epoch
    TN, FP, FN, TP = confusion[0,0], confusion[0,1], confusion[1,0], confusion[1,1] 
IndexError: index 1 is out of bounds for axis 1 with size 1

print(confusion) is [[3014656]]
It is caused by only one category?

**Comment by JCruan519** [comment]
Hello, that should be the case because we didn't consider the scenario of a single category during training and testing.
